### ISSUE TITLE
TypeError: Cannot read property 'listen' of undefined

### ISSUE THREAD

**Issue by gciluffo** [simonh1000/angular-http-server#10]
Trying to use the --https flag and getting:

```
 dist git:(master) ✗ angular-http-server --https 

Info: Path not specified using the working directory.
/usr/local/lib/node_modules/angular-http-server/angular-http-server.js:33
server.listen(getPort(), function () {
       ^

TypeError: Cannot read property 'listen' of undefined
    at Object.<anonymous> (/usr/local/lib/node_modules/angular-http-server/angular-http-server.js:33:8)
    at Module._compile (module.js:612:30)
    at Object.Module._extensions..js (module.js:623:10)
    at Module.load (module.js:531:32)
    at tryModuleLoad (module.js:494:12)
    at Function.Module._load (module.js:486:3)
    at Function.Module.runMain (module.js:653:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
```

I simply did ng build --prod on an ng2 project, cd and then ran `angular-http-server --https`

**Comment by simonh1000** [comment]
whoops, sorry, have pushed a fix

**Comment by gciluffo** [comment]
Thank you for the quick response. Im still seeing the same issue on 1.4.2. Can you confirm?
