### ISSUE TITLE
SyntaxError: Block-scoped declarations error

### ISSUE THREAD

**Issue by lamba92** [simonh1000/angular-http-server#11]
Whatever are the arguments the output is:

```
/usr/local/lib/node_modules/angular-http-server/angular-http-server.js:70
            let ct = mime.lookup(possibleFilename);
            ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3
```

I'm on Ubuntu 16.04.3

**Comment by greenygh0st** [comment]
Do you have an example of any arguments you are providing and also what version of Node are you running?

**Comment by simonh1000** [comment]
What version of node are you using? (I don't have any problems with 8 but I accept that I may need to make that a dependency to avoid this error occurring)

**Comment by simonh1000** [comment]
Going to close
