### ISSUE TITLE
TypeError: path must be a string or Buffer

### ISSUE THREAD

**Issue by jordimx** [simonh1000/angular-http-server#8]
Hi!
When I try to load the app in the browser, the server stops working and throws this error.

```
Route dummy, replacing with index.html
fs.js:652
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

TypeError: path must be a string or Buffer
    at Object.fs.openSync (fs.js:652:18)
    at Object.fs.readFileSync (fs.js:553:33)
    at returnDistFile (/usr/local/lib/node_modules/angular-http-server/angular-http-server.js:99:15)
    at /usr/local/lib/node_modules/angular-http-server/angular-http-server.js:66:26
    at FSReqWrap.oncomplete (fs.js:152:21
```

Thanks!

**Comment by greenygh0st** [comment]
@simonh1000 I'll happily take a look at this. The PR I am working on adds a bunch of error checking anyways. 😄

**Comment by simonh1000** [comment]
should be fixed now
